Models/Document.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Kennisbank.Models
{
    public class Document
    {
        public int Id { get; set; }

        [Display(Name = "File Name")]
        public string Name { get; set; }
        public string Tag { get; set; }

        [Display(Name = "File Size")]
        public long FileSize { get; set; }

        [Display(Name = "Added On")]
        [DataType(DataType.Date)]
        public DateTime AddedOn { get; set; }

        [Display(Name = "Last Edited")]
        [DataType(DataType.Date)]
        public DateTime LastEdited { get; set; }

        [Display(Name = "Owner")]
        public string AddedBy { get; set; }

        public string FilePath { get; set; }
    }
}

Models/DocumentViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Kennisbank.Models
{
    public class DocumentViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Tag { get; set; }
        public long FileSize { get; set; }
        public DateTime AddedOn { get; set; }
        public DateTime LastEdited { get; set; }
        public string AddedBy { get; set; }
        public SelectList Tags { get; set; }
    }
}

Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kennisbank.Data;
using Kennisbank.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Kennisbank.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly KennisbankContext _context;
        private readonly IWebHostEnvironment webHostEnvironment;

        public DocumentsController(KennisbankContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            this.webHostEnvironment = webHostEnvironment;
        }

        // GET: Documents
        public async Task<IActionResult> Index(string documentTag, string searchString)
        {
            var tagQuery = from d in _context.Document
                           orderby d.Tag
                           select d.Tag;

            var documents = from d in _context.Document
                            select d;

            if (!String.IsNullOrEmpty(searchString))
            {
                documents = documents.Where(s => s.AddedBy.Contains(searchString) || s.Name.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(documentTag))
            {
                documents = documents.Where(x => x.Tag == documentTag);
            }

            var documentTagVM = new DocumentTagViewModel
            {
                Tags = new SelectList(await tagQuery.Distinct().ToListAsync()),
                Documents = await documents.ToListAsync()
            };

            return View(documentTagVM);
        }

        // GET: Documents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Document
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // GET: Documents/Create
        public async Task<IActionResult> Create()
        {
            var tags = from t in _context.Tag
                           orderby t.Name
                           select t.Name;

            var documentVM = new DocumentViewModel
            {
                Tags = new SelectList(await tags.Distinct().ToListAsync())
            };

            return View(documentVM);
        }

        // POST: Documents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DocumentViewModel documentVM, IFormFile file)
        {
            var document = new Document { };

            if (ModelState.IsValid)
            {
                var fileSize = file.Length;

                if (fileSize > 0)
                {
                    var folder = Path.Combine(webHostEnvironment.WebRootPath, "files");
                    var uniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                    var filePath = Path.Combine(folder, uniqueFileName);

                    using var stream = new FileStream(filePath, FileMode.Create);
                    await file.CopyToAsync(stream);

                    document = new Document
                    {
                        Name = file.FileName,
                        FileSize = file.Length,
                        Tag = documentVM.Tag,
                        AddedBy = "mike", // temporary placeholder until actual login is added.
                        AddedOn = DateTime.Now,
                        LastEdited = DateTime.Now,
                        FilePath = uniqueFileName
                    };
                }

                _context.Add(document);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(document);
        }

        // GET: Documents/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Document.FindAsync(id);
            
            if (document == null)
            {
                return NotFound();
            }

            var tags = from t in _context.Tag
                       orderby t.Name
                       select t.Name;

            var documentVM = new DocumentViewModel
            {
                Id = document.Id,
                Name = document.Name,
                FileSize = document.FileSize,
                AddedBy = document.AddedBy,
                AddedOn = document.AddedOn,
                LastEdited = document.LastEdited,
                Tag = document.Tag,
                Tags = new SelectList(await tags.Distinct().ToListAsync())
            };

            //return View(documentVM);
            return View(documentVM);
        }

        // POST: Documents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, AddedOn, Tag, AddedBy, FileSize")] Document document, IFormFile file)
        {
            if (id != document.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file == null)
                    {
                        document.Name = document.Name;
                        document.Tag = document.Tag;
                        document.AddedBy = document.AddedBy;
                        document.LastEdited = DateTime.Now;

                        _context.Update(document);
                        await _context.SaveChangesAsync();
                    }
                    else if (file.Length > 0)
                    {
                        var folder = Path.Combine(webHostEnvironment.WebRootPath, "files");
                        var uniqueFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                        var filePath = Path.Combine(folder, uniqueFileName);

                        using var stream = new FileStream(filePath, FileMode.Create);
                        await file.CopyToAsync(stream);
                    
                        document.Name = file.FileName;
                        document.FileSize = file.Length;
                        document.Tag = document.Tag;
                        document.AddedOn = document.AddedOn;
                        document.LastEdited = DateTime.Now;
                        document.AddedBy = document.AddedBy;
                        document.FilePath = uniqueFileName;

                        _context.Update(document);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DocumentExists(document.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(document);
        }

        // GET: Documents/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var document = await _context.Document
                .FirstOrDefaultAsync(m => m.Id == id);
            if (document == null)
            {
                return NotFound();
            }

            return View(document);
        }

        // POST: Documents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var document = await _context.Document.FindAsync(id);
            _context.Document.Remove(document);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Download(string filename)
        {
            if (filename != null)
            {
                var filepath = Path.Combine(webHostEnvironment.WebRootPath, "files", filename);
                var memory = new MemoryStream();

                using var stream = new FileStream(filepath, FileMode.Open);
                await stream.CopyToAsync(memory);

                return File(memory, GetContentType(filepath), Path.GetFileName(filepath).Remove(0, 37));
            }

            return Content("filename not present");
        }

        private string GetContentType(string path)
        {
            var types = GetMimeTypes();
            var ext = Path.GetExtension(path).ToLowerInvariant();
            return types[ext];
        }

        private Dictionary<string, string> GetMimeTypes()
        {
            return new Dictionary<string, string>
            {
                {".txt", "text/plain"},
                {".pdf", "application/pdf"},

Views/Documents/Create.cshtml
@model Kennisbank.Models.DocumentViewModel

@{
    ViewData["Title"] = "Create";
}

<h1 class="text-cim">Documents</h1>

<h4>Create</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-controller="Documents" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">File</label><br />
                <input class="" type="file" name="file" />
            </div>
            <div class="form-group">
                <label asp-for="Tag" class="control-label"></label>
                <select asp-for="Tag" asp-items="Model.Tags" class="form-control"></select>
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-cim" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Documents/Delete.cshtml
@model Kennisbank.Models.Document

@{
    ViewData["Title"] = "Delete";
}

<h1 class="text-cim">Documents</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddedOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AddedBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AddedBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileSize)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileSize)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Documents/Details.cshtml
@model Kennisbank.Models.Document

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-cim">Documents</h1>

<div>
    <h4>Details</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Documents" asp-action="Download" asp-route-filename="@Model.FilePath">@Html.DisplayFor(model => model.Name)</a>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tag)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AddedBy)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AddedBy)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastEdited)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastEdited)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AddedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AddedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FileSize)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FileSize)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Documents/Edit.cshtml
@model Kennisbank.Models.DocumentViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-cim">Documents</h1>

<h4>Edit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data" asp-controller="Documents" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="AddedOn" />
            <input type="hidden" asp-for="AddedBy" />
            <input type="hidden" asp-for="FileSize" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">Current File</label>
                <input asp-for="Name" class="form-control" readonly />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">New File</label><br />
                <input class="" type="file" name="file" />
            </div>
            <div class="form-group">
                <label asp-for="Tag" class="control-label">Tag - Previous Tag: @Model.Tag</label>
                <select asp-for="Tag" asp-items="Model.Tags" class="form-control"></select>
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-cim" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Documents/Index.cshtml
@model Kennisbank.Models.DocumentTagViewModel

@{
    ViewData["Title"] = "Documents";
}

<h1 class="text-cim">Documents</h1>

<p>
    <a class="btn btn-cim" role="button" asp-controller="Documents" asp-action="Create">Add a Document</a>
</p>

<form asp-controller="Documents" asp-action="Index" method="get">
    <p>
        Tag:
        <select asp-for="DocumentTag" asp-items="Model.Tags">
            <option value="">All</option>
        </select>
        Name / Owner: 
        <input type="text" name="searchString" />
        <input type="submit" value="Search" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Documents[0].Name)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Documents[0].Tag)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documents[0].AddedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documents[0].LastEdited)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documents[0].AddedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Documents[0].FileSize)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Documents) 
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Tag)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AddedBy)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastEdited)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AddedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FileSize)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Documents/UploadFile.cshtml
@{
    ViewData["Title"] = "Upload a File";
}

<h1>Upload a File</h1>

<div class="row">
    <div class="col-md-10">
        <form methods="post" enctype="multipart/form-data" asp.controller="Documents" asp-action="UploadFile">
            <div class="form-group">
                <div class="col-md-10">
                    <p>Upload a file using this form:</p>
                    <input type="file" name="files" />
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Upload" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>